version: '3'

services:
  # Serviço do PHP com Laravel
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: laravel-app
  #   container_name: laravel-app
  #   restart: unless-stopped
  #   tty: true
  #   environment:
  #     SERVICE_NAME: app
  #     SERVICE_TAGS: dev
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
  #     - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #   networks:
  #     - laravel

  # # Serviço do Nginx
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - laravel

  # Serviço do MySQL
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: douglas  
      MYSQL_PASSWORD: 123456  
      MYSQL_ROOT_PASSWORD: 123456  
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - minhanetwork

# Rede
networks:
  minhanetwork:
    driver: bridge
